<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Категория не найдена' => 'Category not found',
    'English' => 'English',
    'ID' => 'ID',
    'Depth' => 'Depth',
    'Lft' => 'Lft',
    'Rgt' => 'Rgt',
    'Root' => 'Root',
    'Алиас' => 'Alias',
    'Выберите статус' => 'Select status',
    'Добавление' => 'Adding',
    'Категории' => 'Categories',
    'Название' => 'Name',
    'Название (EN)' => 'Description (EN)',
    'Название (RU)' => 'Description (RU)',
    'Общая информация' => 'General Information',
    'Описание' => 'Description',
    'Описание (EN)' => 'Description (EN)',
    'Описание (RU)' => 'Description (RU)',
    'Поиск' => 'Search',
    'Просмотр' => 'View',
    'Редактирование' => 'Edit',
    'Родительская категория' => 'Parent category',
    'Русский' => 'Russian',
    'Сбросить' => 'Reset',
    'Статус' => 'Status',
    'Структура' => 'Structure',
];
