<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Команда' => '',
    'Команда/ Просмотр' => '',
    ' Друзья' => 'Friends',
    '+ Сообщение' => '+ Message',
    'Ваш отказ стать другом {friend} принят!' => 'Your refusal sat another {friend} passed!',
    'Воспользуйтесь поиском и добавьте друзей в свою коллекцию' => 'Use search and add friends to your collection',
    'Заявки в друзья' => 'Friend Requests',
    'Мои заявки' => 'My application',
    'Мои контакты' => 'My Contacts',
    'НАПИСАТЬ ПИСЬМО' => 'WRITE THE LETTER',
    'Написать' => 'Write',
    'Ничего не найдено' => 'Nothing was found',
    'Отмена' => 'Cancel',
    'Отправить' => 'Send',
    'ПОЛУЧАТЕЛЬ' => 'RECIPIENT',
    'Пользователь {name} был удален окончательно!' => 'User {name} has been removed completely!',
    'Пользователь {name} добавил вас в друзья' => 'User {name} has added you as a friend',
    'Пользователь {name} отказался стать вашим другом' => 'User {name} refused to be your friend',
    'Пользователь {name} стал вашим другом' => 'User {name} has become your friend',
    'Пользователь {name} удалил вас из друзей' => 'User {name} has removed you from friends',
    'Пользователь {name} уже в списке ваших друзей' => 'User {name} already in the list of your friends',
    'Пользователю {name} уже было отправлено приглашение стать вашим другом' => 'User {name} already sent an invitation to be your friend',
    'Пользователю {name} успешно отправленно приглашение стать вашим другом' => 'User {name} successfully sent an invitation to be your friend',
    'Сообщение' => 'Message',
    'У вас нет друзей' => 'You have no friends',
    'заявки' => 'orders',
    'мои друзья' => 'My Friends',
    'отправить' => 'send',
];
