<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Блок не найден' => '',
    'Дубликат steam_id: {steam_id}' => '',
    'Реверсивный результат' => '',
    'Сброс игры' => '',
    '(не задано)' => '(not set)',
    'Blog' => 'Blog',
    'Email администратора' => 'Administrator\'s email',
    'English' => 'English',
    'Facebook' => 'Facebook',
    'ID' => 'ID',
    'ID модуля' => 'Module\'s ID',
    'Twitter' => 'Twitter',
    'YouTube' => 'YouTube',
    '{0, date, dd MMMM YYYY HH:mm}' => '{0, date, dd MMMM YYYY HH:mm}',
    'Август' => 'August',
    'Администратор' => 'Administrator',
    'Апрель' => 'April',
    'Вас нет в списке участников бета тестирования' => 'You are not in the list of participants in the beta testing',
    'Ваш браузер не поддерживает элемент "audio"' => 'Your browser does not support element "audio"',
    'Вконтакте' => 'Vkontakte',
    'Внутренняя ошибка сервера' => 'Internal server error',
    'Время жизни кеша (сек.)' => 'Cache lifetime (in sec.)',
    'Вы уверены что хотите очистить кеш?' => 'Are you sure you want to clear the cache?',
    'Вы уверены, что хотите удалить этот элемент?' => 'Are you sure you want to delete this item?',
    'Выход' => 'Logout',
    'Главная' => 'Home',
    'Главная страница' => 'Home page',
    'Да' => 'Yes',
    'Декабрь' => 'December',
    'Для работы модуля <b>{moduleName}</b> необходимо включить модуль <b>{dep}</b>' => 'For the work of the module <b>{moduleName}</b> You must enable module <b>{dep}</b>',
    'Добавить' => 'Add',
    'Закрыть' => 'Close',
    'Значение' => 'Value',
    'Изменения успешно сохранены' => 'Changes saved successfully',
    'Июль' => 'July',
    'Июнь' => 'June',
    'Кеш успешно удален' => 'The cache is deleted successfully',
    'Ключевые слова' => 'Keywords',
    'Май' => 'May',
    'Март' => 'March',
    'Модули' => 'Modules',
    'Модуль не найден' => 'Module not found',
    'Название сайта' => 'Site Name',
    'Настройки' => 'Settings',
    'Настройки для модуля "{module}" успешно сохранены!' => 'Settings for the module "{module}" successfully saved!',
    'Настройки модуля "{title}"' => 'Module Settings "{title}"',
    'Настройки сайта' => 'Site Settings',
    'Настройки успешно сброшены' => 'Settings successfully reset',
    'Не опубликовано' => 'Not published',
    'Необходимо авторизоваться' => 'Authorization required',
    'Необходимо подождать некоторое время, прежде чем отправлять повторный комментарий' => 'You should wait a while before posting repeated comment',
    'Нет' => 'No',
    'Нет сообщений' => 'No messages',
    'Ноябрь' => 'November',
    'Общая информация' => 'General Information',
    'Октябрь' => 'October',
    'Описание сайта' => 'Site Description',
    'Опубликовано' => 'Published',
    'Основные настройки' => 'Basic Settings',
    'Оставьте поле пустым, чтобы автоматически сгенерировать из названия' => 'Leave field blank to automatically generate the name',
    'Отмена' => 'Cancel',
    'Очистить кеш' => 'Clear cache',
    'Ошибка' => 'Error',
    'Панель управления' => 'Control Panel',
    'Параметр' => 'Option',
    'Перейти на сайт' => 'Go to site',
    'Переключить навигацию' => 'Toggle navigation',
    'Последние пользователи' => 'Last users',
    'Посмотреть' => 'View',
    'Произошла ошибка при сохранении настроек. Возможно вы ввели недопустимые значения для полей (строку заместо числа).' => 'An error occurred when saving settings. Perhaps you\'ve entered invalid values ​​for fields (sting instead of nubber)',
    'Редактировать' => 'Edit',
    'Русский' => 'Russian',
    'Сентябрь' => 'September',
    'Система' => 'System',
    'Страница не найдена' => 'Page not found',
    'У вас нет прав на данное действие' => 'You are not allowed on this action.',
    'У модуля "{title}" нет доступных для редактирования параметров' => 'In the module "{title}" No editable parameters',
    'У модуля нет настроек' => 'Do not have the module settings',
    'Удалить' => 'Delete',
    'Февраль' => 'February',
    'Чат' => 'Chat',
    'Январь' => 'January',
];
