<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Blog' => 'Blog',
    'Facebook' => 'Facebook',
    'ID' => 'ID',
    'ID обсуждения' => 'Discussion ID',
    'ID пользователя' => 'User ID',
    'Twitter' => 'Twitter',
    'YouTube' => 'YouTube',
    '{0, date, MMMM}' => '{0, date, MMMM}',
    'Алиас' => 'Alias',
    'Без ответов' => 'Without answers',
    'Вконтакте' => 'Vkontakte',
    'Вопрос' => 'Question',
    'Вопрос успешно добавлен' => 'Question has been added successfully',
    'Вопросов на страницу' => 'Questions per page',
    'Все' => 'All',
    'Вы можете задать свой вопрос{br}сообществу '.Yii::$app->name => 'You can ask your question{br}to '.Yii::$app->name.' community',
    'Дата редактирования' => 'Updated at',
    'Дата создания' => 'Created at',
    'Добавить отзыв или предложение' => 'Add comment or suggestion',
    'ЗАДАТЬ ВОПРОС' => 'ASK QUESTION',
    'Заголовок' => 'Title',
    'К сожалению, нет ни одного комментария' => 'Unfortunately, there is no comments',
    'КЛЮЧЕВЫЕ СЛОВА' => 'KEYWORDS',
    'Количество комментариев' => 'Number of comments',
    'Комментариев на страницу' => 'Comments per page',
    'Комментарии' => 'Comments',
    'Комментарий успешно добавлен' => 'Comment has been added successfully',
    'Настройки списков' => 'List settings',
    'Не нравится' => 'Dislike',
    'Нравится' => 'Like',
    'ОБСУЖДЕНИЯ' => 'DISCUSSIONS',
    'Обсуждение вопроса' => 'Discussion',
    'Обсуждения' => 'Discussions',
    'Отмена' => 'Cancel',
    'ПОКАЗАТЬ ЕЩЕ' => 'SHOW MORE',
    'Поделиться' => 'Share',
    'Пользователи' => 'Users',
    'Разрешено комментировать только на русском языке. Запрещено использовать мат, транслит.' => 'Allowed to comment only in Russian. Prohibited use mat, transliteration.',
    'С ответами' => 'With answers',
    'СТАТУС' => 'STATUS',
    'Сбросить все' => 'Reset all',
    'Содержимое' => 'Content',
    'Статус' => 'Status',
    'Текст' => 'Text',
    'Тема' => 'Subject',
    'вопросов' => 'questions',
    'добавить комментарий' => 'add comment',
    'задать вопрос' => 'ask question',
    'отправить' => 'send',
    'показать' => 'show',
];
