<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '0 - fail, 1-succes' => '',
    '0-ввод/1- вывод' => '',
    '<span style="color:red">Отменена</span>' => '<span style="color:red">Cancelled</span>' ,
    'АВС' => '',
    'В пополнение средств отказано, подождите 10 сек , убедитесь в правильности ввода данных , #: {n}' => 'In the replenishment denied, wait 10 seconds, verify the correctness of the data entry, #: {n}',
    'Вывод средств - Robokassa' => 'Income = Robokassa',
    'ДО' => 'TO',
    'ОТ' => 'FROM',
    'ПОКАЗАТЬ ЗА ПЕРИОД' => 'Show for period',
    'Пополнение счета - Robokassa' => 'Recharge - Robokassa',
    'Проведена' => 'approved ',
    'Сбросить все' => 'Reset All',
    'на вашем счету:' => 'your account:',
    'показать' => 'show',
    '0 - не подтвержд, 1-подтвржд' => '0 - rejected , 1-approved',
    '0-ввод, 1- вывод' => '0-income , 1- out',
    'Amount' => 'Сумма',
    'Created At' => 'Cозданно',
    'ID' => 'ID',
    'Transaction ID' => 'Id трансакции',
    'User ID' => 'Id пользователя',
    'User Name' => 'Имя пользователя',
    'В пополнение средств отказано, подождите 10 сек , убедитесь в правильности ввода данных , код ошибки: {error}' => 'In replenishment denied, wait 10 seconds, make sure the correct data entry error code: {error}',
    'ВВОД СРЕДСТВ' => 'Deposit funds',
    'ВЫВОД СРЕДСТВ' => 'Withdrawal of funds',
    'Ваше баланс пополнился на ${sum} ' => 'Your balance is added to the $ {sum}',
    'Владелец карты' => 'Cardholder',
    'Время создания' => 'Time to create',
    'ИСТОРИЯ ПЛАТЕЖЕЙ' => 'PAYMENT HISTORY',
    'Имя пользователя' => 'User name',
    'Код проверки' => 'Verification code',
    'Пользователь ID' => 'User ID',
    'СРЕДСТВА' => 'FUNDS',
    'Сумма' => 'Amount',
    'Тип карты' => 'Card type',
    'Транзакция ID' => 'ransaction ID',
    'Финансовые операции / Ввод средств' => 'Financial Operations / Deposit Funds',
    'Финансовые операции / Вывод средств' => 'Financial Operations / Withdrawal',
    'Финансовые операции / История платежей' => 'Financial Operations / Payment History',
    'Финансовые операции / Средства' => 'Financial Operations / Funds',
];
