<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Раздел в стадии наполнения' => '',
    'E-mail' => 'E-mail',
    'English' => 'English',
    'FAQ' => 'FAQ',
    'ID' => 'ID',
    'IP' => 'IP',
    'Алиас' => 'Alias',
    'Ваш вопрос успешно отправлен' => 'Your questions has been sent successfully',
    'Введите число' => 'Enter the number',
    'Вопрос' => 'Question',
    'Вопрос (EN)' => 'Question (EN)',
    'Вопрос (RU)' => 'Question (RU)',
    'Вопрос не найден' => 'The question can not be found',
    'Выберите статус' => 'Select status',
    'Дата добавления' => 'Created at',
    'Дата обновления' => 'Updated',
    'Дата ответа' => 'Reply date',
    'Дата редактирования' => 'Updated at',
    'Дата создания' => 'Create data',
    'Добавление' => 'Adding',
    'Задать вопрос' => 'Ask a question',
    'Имя' => 'Name',
    'Инструкция пользователю' => 'Instruction for user',
    'Категория' => 'Category',
    'Код' => 'Code',
    'Не прочитано' => 'Don\'t read',
    'Обратная связь' => 'Feedback',
    'Общая информация' => 'General information',
    'Ответ' => 'Answer',
    'Ответ (EN)' => 'Answer (EN)',
    'Ответ (RU)' => 'Answer (RU)',
    'Ответ на вопрос с формы обратной связи' => 'Answer to question from the feedback form',
    'Ответ успешно отправлен' => 'Answer has been sent successfully',
    'Ответить на сообщение' => 'Reply to message',
    'Отправить' => 'Send',
    'Отправлен ответ' => 'Replied to',
    'Поиск' => 'Search',
    'Пользователь' => 'User',
    'Помощь' => 'Help',
    'Просмотр' => 'View',
    'Прочитано' => 'Read',
    'Редактирование' => 'Editing',
    'Руководство' => 'Manual',
    'Руководство не найдено' => 'Manual not found',
    'Русский' => 'Russian',
    'Сбросить' => 'Reset',
    'Статус' => 'Status',
    'Структура' => 'Structure',
    'Тема' => 'Subject',
    'Язык' => 'Language',
];
