<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Был отправлен запрос на восстановление пароля на {0}' => 'Request was sent to recover a password for {0}',
    'В очереди' => 'In queue',
    'Ваш аккаунт на {0} был успешно создан' => 'Your account on {0} has been successfully created',
    'Ваш пароль' => 'Your password',
    'Вы недавно запросили смену e-mail на {0}' => 'You recently requested a change e-mail to {0}',
    'Дата отправки' => 'Send date',
    'Дата создания' => 'Create date',
    'Если вы не отправляли этот запрос, проигнорируйте это письмо. Ваш аккаунт в безопасности' => 'If you did not initiate this request, please ignore this message. Your account security',
    'Если вы получили это письмо по ошибке, просто удалите его' => 'If you have received this email by error, just delete it',
    'Здравствуйте' => 'Hello',
    'Отправитель' => 'Sender',
    'Отправлено' => 'Submitted',
    'Ошибка' => 'Error',
    'Параметры для шаблона' => 'Params for template',
    'Письмо не найдено' => 'Mail not found',
    'Поиск' => 'Search',
    'Получатель' => 'Receiver',
    'Пользователи' => 'Users',
    'Почта' => 'E-mail',
    'Просмотр' => 'View',
    'Путь к шаблону' => 'Template path',
    'Сбросить' => 'Reset',
    'Содержимое' => 'Body',
    'Спасибо за регистрацию на {0}' => 'Thank you for registering on {0}',
    'Статус' => 'Status',
    'Тема' => 'Subject',
    'Чтобы восстановить пароль, нажмите на ссылку ниже' => 'In order to recover your password, click on the link below',
    'Чтобы завершить запрос, нажмите на ссылку ниже' => 'To complete the request, click on the link below',
    'Чтобы завершить регистрацию, нажмите на ссылку ниже' => 'To complete your registration, click on the link below',
    'Чтобы завершить смену пароля, мы должны удостовериться, что именно вы его начали' => 'To complete the password change, we need to make sure it was you started',
    'Шаблон' => 'Template',
    'Эта ссылка будет действовать ограниченное количество времени' => 'This link will operate a limited amount of time',
    'в очереди:' => 'in queue',
];
