<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Позиция' => '',
    'English' => 'English',
    'HTML код' => 'HTML code',
    'HTML код баннера' => 'Banner HTML code',
    'ID' => 'ID',
    'ID слайдера' => 'Slider ID',
    'Баннер не найден' => 'Banner not found',
    'Баннеры' => 'Banners',
    'Вы действительно хотите удалить изображение?' => 'Do you really want to delete the image?',
    'Выберите статус' => 'Select status',
    'Выберите тип баннера' => 'Select banner type',
    'Выберите шаблон' => 'Select template',
    'Добавление' => 'Adding',
    'Дополнительные параметры' => 'Additional options',
    'Загрузить' => 'Upload',
    'Загрузить изображения' => 'Upload images',
    'Загрузка' => 'Uploading',
    'Загрузка изображений' => 'Images uploading',
    'Изображение' => 'Image',
    'Изображения с таким ID не существует' => 'Image with this ID doesn\'t exist',
    'Код' => 'Code',
    'Код для вставки в шаблон' => 'Code for use in template',
    'Код для вставки слайдера в шаблон' => 'Code for use slider in template',
    'Количество просмотров' => 'Views count',
    'Контент' => 'Content',
    'Медиа' => 'Media',
    'Модель не найдена' => 'Model not found',
    'Название' => 'Title',
    'Название (EN)' => 'Title (EN)',
    'Название (RU)' => 'Title (RU)',
    'Не получен обязательный параметр "ID"' => 'Not obtained a required parameter "ID"',
    'Не правильный тип баннера' => 'Invalid banner type',
    'Не удалось загрузить файл' => 'Uploading file error',
    'Не удалось сохранить изображение в БД' => 'Can\'t save image into DB',
    'Не удалось сохранить изображение на диск' => 'Can\'t save image into disk',
    'Общая информация' => 'General information',
    'Отмена' => 'Cancel',
    'Отменить' => 'Cancel',
    'Ошибка' => 'Error',
    'Поиск' => 'Search',
    'Показать дополнительные параметры' => 'Show additional params',
    'Показать информацию о слайдере' => 'Show slider info',
    'Просмотр' => 'View',
    'Редактирование' => 'Update',
    'Русский' => 'Russian',
    'Сбросить' => 'Reset',
    'Слайдер не найден' => 'Slider not found',
    'Слайдеры' => 'Sliders',
    'Ссылка' => 'Link',
    'Статус' => 'Status',
    'Тип баннера' => 'Banner type',
    'Удалить' => 'Delete',
    'Что-то не так с файлом изображения...' => 'Something is wrong with the image file ...',
];
