<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Зарегистрироваться в турнире' => '',
    'Как это работает?' => '',
    'Смотреть таблицу' => '',
    'Турниры' => '',
    'Чат' => '',
    'Я хочу стать участником турнира' => '',
    'E-mail' => 'E-mail',
    'Mirprost' => 'Mirprost',
    'OK' => 'OK',
    'Быстрая регистрация' => 'Quick registration',
    'ВАШ E-MAIL' => 'YOUR E-MAIL',
    'ВВЕДИТЕ ЧИСЛО' => 'Enter a number',
    'ВОЙТИ' => 'LOGIN',
    'ВОССТАНОВИТЬ' => 'RESET',
    'ВОССТАНОВЛЕНИЕ ПАРОЛЯ' => 'PASSWORD RECOVERY',
    'Вакансии' => 'Jobs',
    'Введите число' => 'Enter a number',
    'Все игры' => 'All games',
    'Все права защищены' => 'All rights reserved',
    'Забыли пароль?' => 'Forgot password?',
    'Запомнить' => 'Remember Me',
    'Играй прямо сейчас >>' => 'Play now >>',
    'Игры' => 'Games',
    'Информация' => 'Information',
    'Как это<br> работает?' => 'How it<br> works?',
    'Книга отзывов и предложений' => 'Book reviews and suggestions',
    'Контакты' => 'Contacts',
    'Логин' => 'Login',
    'Логин или E-mail' => 'Username or E-mail',
    'Мне есть 18 лет' => 'I am 18 years',
    'На главную' => 'Home page',
    'Новости' => 'News',
    'Новости проекта' => 'Project News',
    'О Mirprost' => 'About us',
    'ОТКАЗАНО В ДОСТУПЕ' => 'Access Denied',
    'Обсуждения' => 'Discussions',
    'Отмена' => 'Cancel',
    'Пароль' => 'Password',
    'Повторите пароль' => 'Confirm password',
    'Политика конфиденциальности' => 'Privacy Policy',
    'Пользовательское соглашение' => 'Agreement',
    'Помощь' => 'Help',
    'РЕГИСТРАЦИЯ' => 'REGISTRATION',
    'Рекламодателям' => 'For advertisers',
    'Руководство' => 'Leaders',
    'СТРАНИЦА НЕ НАЙДЕНА' => 'PAGE NOT FOUND',
    'Я прочитал <a href="{url}" target="_blank">пользовательское соглашение</a> и согласен с условиями' => 'I read <a href="{url}" target="_blank">User Agreement</a> and agree to the terms and conditions',
    'Я прочитал <a href="{url}" target="_blank">пользовательское соглашение</a><br>и согласен с условиями' => 'I have read <a href="{url}" target="_blank"> User Agreement</a><br> and agree to the terms',
    'играть' => 'play',
];
