<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'English' => 'English',
    'ID' => 'ID',
    'Алиас' => 'Alias',
    'Вы должны авторизироваться, чтобы просмотреть данную страницу.' => 'You must login to view this page',
    'Выберите статус' => 'Select status',
    'Дата редактирования' => 'Date of editing',
    'Дата создания' => 'Date',
    'Добавление' => 'Adding',
    'Запрашиваемая страница не найдена' => 'he requested URL was not found',
    'Изображение' => 'Image',
    'Контент' => 'Content',
    'Максимальный размер (в байтах)' => 'Maximum size (in bytes)',
    'Минимальный размер (в байтах)' => 'The minimum size (in bytes)',
    'Название' => 'Name',
    'Название (EN)' => 'Name (EN)',
    'Название (RU)' => 'Name (RU)',
    'Настройки изображений' => 'mage Settings',
    'Общая информация' => 'General Information',
    'Поиск' => 'Search',
    'Пользователь' => 'User',
    'Просмотр' => 'View',
    'Редактирование' => 'Edit',
    'Русский' => 'Russian',
    'Сбросить' => 'Reset',
    'Содержимое' => 'Content',
    'Содержимое (EN)' => 'Content (EN)',
    'Содержимое (RU)' => 'Content (RU)',
    'Содержимое в файле' => 'The content of the file',
    'Статус' => 'Status',
    'Страница не найдена' => 'Page not found',
    'Страницы' => 'Pages',
    'Только для зарегистрированных' => 'Only for registered',
    'Шаблон' => 'Template',
];
