<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'English' => 'English',
    'ID' => 'ID',
    'Алиас' => 'Alias',
    'Выберите статус' => 'Select status',
    'Дата добавления' => 'Created at',
    'Дата редактирования' => 'Updated at',
    'Добавление' => 'Adding',
    'Игра не найдена' => 'Game not found',
    'Игры' => 'Games',
    'Логотип' => 'Logo',
    'Название' => 'Title',
    'Название (EN)' => 'Title (EN)',
    'Название (RU)' => 'Title (RU)',
    'Не удалось сохранить изображение в БД' => 'Unable to save the image into DB',
    'Не удалось сохранить изображение на диск' => 'Unable to save the image to disk',
    'Общая информация' => 'General information',
    'Описание' => 'Description',
    'Описание (EN)' => 'Description (EN)',
    'Описание (RU)' => 'Description (RU)',
    'Поиск' => 'Search',
    'Просмотр' => 'View',
    'Редактирование' => 'Editing',
    'Русский' => 'Russian',
    'Сбросить' => 'Reset',
    'Статус' => 'Status',
    'Структура' => 'Structure',
];
