<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Нет ни одного отзыва' => '',
    'ID пользователя' => 'User ID',
    'Ваш отзыв или{br}предложение' => 'Your review or{br}suggestion',
    'Ваше предложение принято' => 'Your proposal was accepted',
    'Гостевая книга' => 'Guestbook',
    'Дата создания' => 'Created at',
    'Добавить отзыв или предложение' => 'Add review or suggestion',
    'Добавить отзыв{br}или предложение' => 'Add review{br}or suggestion',
    'Добавление' => 'Adding',
    'КНИГА ОТЗЫВОВ И ПРЕДЛОЖЕНИЙ' => 'BOOK REVIEWS AND SUGGESTIONS',
    'Книга отзывов и предложений' => 'Book reviews and suggestions',
    'Настройки списков' => 'Lists settings',
    'Не нравится' => 'Dislike',
    'Нравится' => 'Like',
    'Отзыв #' => 'Rewiew #',
    'Отзыв не найден' => 'Review not found',
    'Отзывов на страницу' => 'Reviews per page',
    'Отзывы' => 'Reviews',
    'Отмена' => 'Cancel',
    'ПО НОВИЗНЕ' => 'BY DATE',
    'ПО РЕЙТИНГУ' => 'BY RATING',
    'Поиск' => 'Search',
    'Пользователи' => 'Users',
    'Просмотр' => 'View',
    'Редактирование' => 'Editing',
    'Сбросить' => 'Reset',
    'Сообщение' => 'Message',
    'Статус' => 'Status',
    'написать' => 'write',
    'отправить' => 'send',
];
