<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID игры' => '',
    'Oзвучен' => '',
    'Вы дали возможность пользователю {username} отправлять вам сообщения' => '',
    'Вы заблокировали возможность пользователю {username} отправлять вам сообщения' => '',
    'Диалога с пользователем {username} невозможен, <a href="javascript:void(0);" onclick="Chat.UnblockUser(' => '',
    'Диалога с пользователем {username} невозможен, пользователь заблокировал вам эту возможность' => '',
    'Диалога с пользователем {username} пуст' => '',
    'Диалога с пользователем {username} удален' => '',
    'НАПИСАТЬ ПИСЬМО {user}' => '',
    'Пользователь {username} приглашает вас в игру.<br> {game} ' => '',
    'Пользователь {username} приглашает вас в команду.<br>{team}' => '',
    ' У Вас пока еще нет друзей' => 'You still do not have friends',
    ' У Вас пока еще нет сообщений' => 'You do not have any messages yet',
    ' У пользователя {username} нет друзей' => 'User {username} have no friends',
    '+ ПРИКРЕПИТЬ' => '+ ATTACH',
    'ID' => 'ID',
    '{0, date, dd MMMM YYYY HH:mm:ss}' => '{0, date, dd MMMM YYYY HH:mm:ss}',
    'Ваше сообщение успешно отправленно' => 'Your message has successfully sent',
    'Ваше сообщение...' => 'Your message ...',
    'Время создания' => 'Time to create',
    'Выберите получателя' => 'Select Recipient',
    'ГОРОД' => 'CITY',
    'Диалога с таким пользователем не существует' => 'Dialogue with the user does not exist',
    'Для успешной отправки сообщения введите имя получателя' => 'To successfully send a message enter the recipient\'s name',
    'Для успешной отправки сообщения введите текст сообщения' => 'To successfully send a message, write the message',
    'Женский' => 'Female',
    'ЛОГИН' => 'Login',
    'Мужской' => 'Male',
    'НАПИСАТЬ ПИСЬМО' => 'WRITE THE LETTER',
    'Нет сообщений' => 'No messages',
    'Открыть чат' => 'Open Chat',
    'Отмена' => 'Cancel',
    'ПОЛУЧАТЕЛЬ' => 'RECIPIENT',
    'Посылающий ID' => 'Sending ID',
    'Почта' => 'Mail',
    'Прикрепленные картинки' => 'Attached images',
    'Принимающий ID' => 'Host ID',
    'Просмотреть профиль подробнее' => 'View profile details',
    'СИСТЕМНЫЕ СООБЩЕНИЯ' => 'SYSTEM MESSAGES',
    'СТАТУС' => 'STATUS',
    'СТРАНА' => 'COUNTRY',
    'Сбросить все' => 'Reset All',
    'Сообщение' => 'Message',
    'Сообщения' => 'Messages',
    'Статус' => 'Status',
    'Тема' => 'Subject',
    'написать письмо' => 'write a letter',
    'ответить' => 'answer',
    'отправить' => 'submit',
    'поиск' => 'search',
    'показать' => 'show',
];
