<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'English' => 'English',
    'ID' => 'ID',
    '{0, date, dd.MM.YY HH:mm}' => '{0, date, dd.MM.YY HH:mm}',
    'Алиас' => 'Alias​​',
    'Выберите статус' => 'Select status',
    'Горячая' => 'Hot',
    'Дата добавления' => 'Date',
    'Дата редактирования' => 'Date of editing',
    'Добавление' => 'Adding',
    'Запрашиваемая страница не найдена' => 'The requested page was not found',
    'Изображение' => 'Image',
    'Категория' => 'Category',
    'Контент' => 'Content',
    'Максимальный размер (в байтах)' => 'Maximum size (in bytes)',
    'Минимальный размер (в байтах)' => 'The minimum size (in bytes)',
    'НОВОСТИ' => 'NEWS',
    'Название' => 'Name',
    'Название (EN)' => 'Name (EN)',
    'Название (RU)' => 'Name (RU)',
    'Настройки изображений' => 'Image Settings',
    'Настройки списков' => 'Settings lists',
    'Новинка' => 'New',
    'Новостей на страницу' => 'News per page',
    'Новости' => 'News',
    'Новость не найдена' => 'News not found',
    'Общая информация' => 'General Information',
    'Поделиться' => 'Share',
    'Поиск' => 'Search',
    'Пользователь' => 'User',
    'Просмотр' => 'View',
    'Редактирование' => 'Editing',
    'Русский' => 'Russian',
    'Сбросить' => 'Reset',
    'Содержимое' => 'Content',
    'Содержимое (EN)' => 'Content (EN)',
    'Содержимое (RU)' => 'Content (RU)',
    'Статус' => 'Statu',
    'Только для зарегистрированных' => 'Only for authorized',
];
