<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Неправильно настроен модуль' => '',
    'Неправильный ID' => '',
    'Неправильный URL' => '',
    'Неправильный тип голоса' => '',
    '"Нравится" + "Не нравится"' => '"Like" + "Dislike"',
    'Голос учтен' => 'Voted successfully',
    'Модуля не существует' => 'Module does not exist',
    'Не удалось проголосовать' => 'Could not vote',
    'Не удалось сохранить изменения' => 'Unable to save changes',
    'Необходимо авторизироваться' => 'Authorization required',
    'Повторное голосование запрещено' => 'Revote forbidden',
    'Разрешено использовать только лайки' => 'Allowed to use likes only',
    'Только "Нравится"' => 'Only "Like"',
    'У текущего модуля нет рейтинга' => 'The current module doesn\'t have rating',
];
