<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'КОМАНДЫ' => 'TEAMS',
    '0 - не начат, 1-начат, 2 - окончен' => '',
    '1-win, 2-lose' => '',
    'Couple With' => '',
    'Created At' => '',
    'Dota' => '',
    'GameID' => '',
    'ID' => '',
    'Team ID' => '',
    'Tournament ID' => '',
    'Tournament Name' => '',
    'Ваш бой "{name1} VS {name2}" состоится в {time}' => '',
    'Ваша команда {team_name} уже зарегестрированна' => '',
    'Ваша команда {team_name} успешно зарегистрирована' => '',
    'Вы не являетесь лидером команды или не состоите в ней! Создайте свою команду.' => '',
    'Имя' => '',
    'Максимальное количество команд' => '',
    'Описание' => '',
    'Турнир не найдена' => '',
    'Турнирный бой' => '',
    'Турниры' => '',
    'Этап турнира' => '',
    'время боя' => '',
];
